### ISSUE TITLE
Kohya works fine with SD1.5 but crashes with SDXL ?!

### ISSUE THREAD

**Issue by web2299** [bmaltais/kohya_ss#3008]
I lost a whole day ... Reinstalled Kohya over 3 times .... Tried with many SDXL models including stable-diffusion-xl-refiner-1.0 and stable-diffusion-xl-base-1.0 and every time i receive this:  Please help me !

File "C:\Kohya\kohya_ss\sd-scripts\sdxl_train.py", line 948, in <module>
    train(args)
  File "C:\Kohya\kohya_ss\sd-scripts\sdxl_train.py", line 217, in train
    ) = sdxl_train_util.load_target_model(args, accelerator, "sdxl", weight_dtype)
  File "C:\Kohya\kohya_ss\sd-scripts\library\sdxl_train_util.py", line 43, in load_target_model
    ) = _load_target_model(
  File "C:\Kohya\kohya_ss\sd-scripts\library\sdxl_train_util.py", line 110, in _load_target_model
    if text_encoder1.dtype != torch.float32:
AttributeError: 'NoneType' object has no attribute 'dtype'
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Kohya\kohya_ss\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "C:\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'C:/Kohya/kohya_ss/sd-scripts/sdxl_train.py', '--config_file', 'D:/123/test\\model/config_dreambooth-20241209-184928.toml']' returned non-zero exit status 1.
18:52:42-914919 INFO     Training has ended.

**Comment by Sylsatra** [comment]
Please provide your config and the full error if possible

**Comment by demiurgen** [comment]
Same problem here. SD15 or SD21 works without any problems but not SDXL. Clean install. Tried two different machines.
